version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: beszel_server_1
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"

  server:
    image: henrygd/beszel:0.1.2@sha256:63d070ae0bf4ce6bdd8ab11b0b1e3b5ca56f7e0a8f2be47f3e55a36f08c6bfa2
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/data
